services:
  pytorch_container:
    build:
      context: .
    container_name: lesion_segmentation_container
    shm_size: '64gb'
    volumes:
      - ${PROJECT_PATH:-./project}:/app
      - ${DATA_PATH:-./data}:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    user: "appuser"
    command: ["python", "main.py"]
